# This docker compose configuration should only be used to override the development compose file, docker-compose.yml

services:
  ui:
    volumes:
      - ./.git:/app/.git:ro
      - ./ui:/app
    entrypoint: ["sh", "-c", "yarn install && yarn start --debug --host 0.0.0.0 --port 4000"]
    environment:
      - CHOKIDAR_USEPOLLING=true
